# hello page
GET http://localhost:3000 HTTP/1.1

### delimiter
# tasks list
GET http://localhost:3000/list HTTP/1.1

###
# create task
POST http://localhost:3000/task HTTP/1.1
content-type: application/json

{
  "text": "this is the new task text2"
}

###
DELETE http://localhost:3000/task/5f3bfe2b7f08450af083748e HTTP/1.1

###
#
OPTIONS http://localhost:3000/task HTTP/1.1

###

PUT http://localhost:3000/task/5f3d4dadc108631f2067af03?state=done HTTP/1.1

###

PUT http://localhost:3000/task/5f3d4dadc108631f2067af03?text=back:create back224 HTTP/1.1
